[build]
builder = "dockerfile"

[deploy]
startCommand = "python backend/api/web_interface.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[env]
FLASK_ENV = "production"
PORT = "${{PORT}}"
PYTHONPATH = "/app"
